// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
      apiKey: "AIzaSyCQksC_EUhpsX31u8I6vJoKPB-hNn31W3Y",
      authDomain: "mentematiko.firebaseapp.com",
      projectId: "mentematiko",
      storageBucket: "mentematiko.appspot.com",
      messagingSenderId: "94206890947",
      appId: "1:94206890947:web:eef34dfb3895ccc026a376",
      measurementId: "G-37DBNRKWTE");
      
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDozA_E7JlpbzOD3WVUnEjAxfGQb0NPk',
    appId: '1:94206890947:android:947e954099bf5b9726a376',
    messagingSenderId: '94206890947',
    projectId: 'mentematiko',
    storageBucket: 'mentematiko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rhRUV6gyBHLP43yogA1J2s9fpnYhYWM',
    appId: '1:94206890947:ios:985d1c2503cc407b26a376',
    messagingSenderId: '94206890947',
    projectId: 'mentematiko',
    storageBucket: 'mentematiko.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rhRUV6gyBHLP43yogA1J2s9fpnYhYWM',
    appId: '1:94206890947:ios:a70a4c49ed7e40a726a376',
    messagingSenderId: '94206890947',
    projectId: 'mentematiko',
    storageBucket: 'mentematiko.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
