// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvxMFwwBYt0db_BDIuu7BSd3s10c01TE',
    appId: '1:687768129774:web:19559580ae28d55c30a3ff',
    messagingSenderId: '687768129774',
    projectId: 'mentematiko-658c7',
    authDomain: 'mentematiko-658c7.firebaseapp.com',
    storageBucket: 'mentematiko-658c7.appspot.com',
    measurementId: 'G-NBGY3VBESR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4l-L6kreUC8GnkkMA6eHtwqE9vE94qA',
    appId: '1:687768129774:android:ad0ccd2dc81ba80c30a3ff',
    messagingSenderId: '687768129774',
    projectId: 'mentematiko-658c7',
    storageBucket: 'mentematiko-658c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbYHh9yrs2lHdo_u3zHxXpisYy6o80rG4',
    appId: '1:687768129774:ios:d2b553de8120383a30a3ff',
    messagingSenderId: '687768129774',
    projectId: 'mentematiko-658c7',
    storageBucket: 'mentematiko-658c7.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbYHh9yrs2lHdo_u3zHxXpisYy6o80rG4',
    appId: '1:687768129774:ios:956d220eb77087b030a3ff',
    messagingSenderId: '687768129774',
    projectId: 'mentematiko-658c7',
    storageBucket: 'mentematiko-658c7.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
