// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZpLCOT2RXOCafkRbgi69dDi86wyoGFas',
    appId: '1:303838311158:web:4a9644910bf630ef80b2d7',
    messagingSenderId: '303838311158',
    projectId: 'mentematiko-d6e5e',
    authDomain: 'mentematiko-d6e5e.firebaseapp.com',
    storageBucket: 'mentematiko-d6e5e.appspot.com',
    measurementId: 'G-P82T3EH1ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVqKbRolCPPilkcM06GhZUXXDK8Iwr80',
    appId: '1:303838311158:android:773e6f321cea181580b2d7',
    messagingSenderId: '303838311158',
    projectId: 'mentematiko-d6e5e',
    storageBucket: 'mentematiko-d6e5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ruYGOw-EJRJ0c4DxUPniYdryu5R9njI',
    appId: '1:303838311158:ios:54043dbf3258278380b2d7',
    messagingSenderId: '303838311158',
    projectId: 'mentematiko-d6e5e',
    storageBucket: 'mentematiko-d6e5e.appspot.com',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ruYGOw-EJRJ0c4DxUPniYdryu5R9njI',
    appId: '1:303838311158:ios:a1ca652bbefcd5ef80b2d7',
    messagingSenderId: '303838311158',
    projectId: 'mentematiko-d6e5e',
    storageBucket: 'mentematiko-d6e5e.appspot.com',
    iosBundleId: 'com.example.card.RunnerTests',
  );
}
